version: "3.8"

services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - SDL_AUDIODRIVER=dummy
      - PYTHONPATH=/usr/src/app
    ports:
      - "8000:8000"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invaders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
